apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurement-api
  namespace: procurement
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: procurement
spec:
  replicas: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: infra
spec:
  replicas: 3
