apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: procurement-secrets
  namespace: procurement
  labels:
    app.kubernetes.io/name: procurement-secrets
    app.kubernetes.io/part-of: procurement-portal
spec:
  encryptedData:
    JWT_SECRET_KEY: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForProcurementApiJwtSecretKey...
    JWT_PUBLIC_KEY: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForProcurementApiJwtPublicKey...
    JWT_PRIVATE_KEY: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForProcurementApiJwtPrivateKey...
    SESSION_SECRET: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForProcurementApiSessionSecret...
    ENCRYPTION_KEY: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForProcurementApiEncryptionKey...
  template:
    metadata:
      name: procurement-secrets
      namespace: procurement
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secrets
  namespace: procurement
  labels:
    app.kubernetes.io/name: postgresql-secrets
    app.kubernetes.io/part-of: procurement-portal
spec:
  encryptedData:
    postgres-user: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForPostgresUser...
    postgres-password: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForPostgresPassword...
    replication-password: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForReplicationPassword...
  template:
    metadata:
      name: postgresql-secrets
      namespace: procurement
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: procurement
  labels:
    app.kubernetes.io/name: redis-secrets
    app.kubernetes.io/part-of: procurement-portal
spec:
  encryptedData:
    redis-password: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForRedisPassword...
  template:
    metadata:
      name: redis-secrets
      namespace: procurement
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secrets
  namespace: procurement
  labels:
    app.kubernetes.io/name: rabbitmq-secrets
    app.kubernetes.io/part-of: procurement-portal
spec:
  encryptedData:
    erlang-cookie: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForRabbitMqErlangCookie...
    rabbitmq-user: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForRabbitMqUser...
    rabbitmq-password: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForRabbitMqPassword...
  template:
    metadata:
      name: rabbitmq-secrets
      namespace: procurement
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secrets
  namespace: procurement
  labels:
    app.kubernetes.io/name: minio-secrets
    app.kubernetes.io/part-of: procurement-portal
spec:
  encryptedData:
    root-user: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForMinioRootUser...
    root-password: AgA+m03y8W5z6V7/ExampleSealedSecretEncryptedDataForMinioRootPassword...
  template:
    metadata:
      name: minio-secrets
      namespace: procurement
    type: Opaque
