apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurement-api
  namespace: procurement
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: procurement
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: procurement
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyer-portal
  namespace: procurement
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-portal
  namespace: procurement
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: procurement
spec:
  replicas: 1
