apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: procurement-portal
spec:
  provider: aws
  objectStorage:
    bucket: procurement-backups
    prefix: velero-backups
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.procurement.svc.cluster.local:9000
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: procurement-portal
spec:
  provider: aws
  config:
    region: minio
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: procurement-daily-backup
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: procurement-portal
spec:
  schedule: "0 2 * * *"
  useOwnerReferencesInBackup: false
  template:
    includedNamespaces:
      - procurement
    includeClusterResources: true
    snapshotVolumes: true
    storageLocation: default
    volumeSnapshotLocations:
      - default
    ttl: 720h0m0s
