apiVersion: v1
kind: Service
metadata:
  name: buyer-portal
  namespace: procurement
  labels:
    app: buyer-portal
    app.kubernetes.io/name: buyer-portal
    app.kubernetes.io/part-of: procurement-portal
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: buyer-portal
---
apiVersion: v1
kind: Service
metadata:
  name: supplier-portal
  namespace: procurement
  labels:
    app: supplier-portal
    app.kubernetes.io/name: supplier-portal
    app.kubernetes.io/part-of: procurement-portal
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: supplier-portal
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: procurement
  labels:
    app: admin-portal
    app.kubernetes.io/name: admin-portal
    app.kubernetes.io/part-of: procurement-portal
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: admin-portal
