name: Deploy to Staging

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build Docker Containers & Staging Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify Docker Compose Build
        run: |
          docker compose -f docker/docker-compose.yml build api buyer-portal supplier-portal admin-portal
